#!/bin/bash
#
# Benutzer hinzufügen
# Ordner erstellen
# Abhängigkeiten installieren
useradd -M faceid
#mkdir /opt/faceid

chown -R faceid:faceid /opt/faceid
pip3 install image face_recognition opencv-python imutils pyzbar requests
#update-rc.d faceid defaults
# anpassen der Dateiberechtigungen
