#!/bin/sh
### BEGIN INIT INFO
# Provides:          faceid
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: FaceID Startup/Monitoring Script
### END INIT INFO

dt=$(date '+%d.%m.%Y %H:%M:%S');
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

exec >> /var/log/faceid.log 2>&1

case "$1" in
  start)
    echo "$dt: Exec faceid with 'start' command"

    if ! ps aux | grep "python3 /opt/faceid/controller/Controller.py" | awk '{print $2}' | head -n 1 > /dev/null
    then
      python3 /opt/faceid/controller/Controller.py &
    fi
    sleep 1
    exit 0
  ;;
  stop)
    echo "$dt: Exec faceid with 'stop' command"
    pid=$(ps aux | grep "python3 /opt/faceid/controller/Controller.py" | awk '{print $2}' | head -n 1)
    sudo kill --signal 2 $pid
    exit 0
    ;;
  restart)
    echo "$dt: Exec faceid with 'restart' command"
    pid=$(ps aux | grep "python3 /opt/faceid/controller/Controller.py" | awk '{print $2}' | head -n 1)
    sudo kill --signal 2 $pid
    sleep 2
    python3 /opt/faceid/controller/Controller.py &
    exit 0
  ;;
  *)
    echo "$dt: /etc/init.d/faceid {start|stop}"
    exit 1
    ;;
esac
